trigger:
- master

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'
  PathToProjects: '**/SampleDDDMicroserviceApp.TransportPeople.Web.API.csproj'

jobs:  
- job: Build
  displayName: Build Powered by YAML
  pool:
    name: TheAgentPool
  steps:
        #task: Use .NET Core sdk 8.x
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 8.x'
      inputs:
        version: 8.x

        #task: Restore
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(PathToProjects)
        vstsFeed: 'f5d0ca62-2bdf-417c-b55e-0f9a8acddc7a'

        #task: Build
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(PathToProjects)
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: False
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
